charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/scripts/reverse-proxy.cli, charts/keycloak/templates/configmap.yaml, charts/keycloak/values.yaml
Proxy address forwarding was directly enabled via CLI but
missed one location. This commit, thus, switches back to
using the environment variable as meant by the Keycloak
Docker image and set the envs var to 'true' by default to
keep the existing behavior.
=> [keycloak] Switch back to using env var PROXY_ADDRESS_FORWARDING

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/statefulset.yaml, charts/keycloak/values.yaml
This avoids environment variables for other services in the
same namespace being injected into the containers which
could issues with the way the Keycloak Docker image handles
environment variables for accessing the database.
Fixes: #9
=> [keycloak] Disable service links by default

charts/keycloak/Chart.yaml, charts/keycloak/templates/test/test-pod.yaml
https://github.com/helm/charts/pull/12795 enabled using an existing secret for the `admin` user of Keycloak. However, the chart tests weren't updated and they still try to use the secret that the chart always used to create.
This PR changes the chart tests so that they use the existing secret specified by the user if it was also used to deploy the chart.
=> [keycloak] Use existing secret for tests when it's also used for deployment

charts/keycloak/Chart.yaml, charts/keycloak/ci/h2-values.yaml
The test adds little value. After all H2 is not
really a suitable database. It is recreated on restarts
and does not support upgrades. However, we'd like to
enable upgrade testing which increases test times
substantially and does not work with H2.
=> [keycloak] Remove H2 test

charts/keycloak/Chart.yaml, charts/keycloak/templates/_helpers.tpl, charts/keycloak/templates/statefulset.yaml
We now expose the generated DNS name of the Keycloak headless-service
via the environment variable KEYCLOAK_SERVICE_DNS_NAME.
This eases the usage of custom jgroups configurations in custom
Keycloak images.
In order to avoid code duplication we introduced a new template function
called `serviceDnsName` accessible via `keycloak.serviceDnsName`.
=> [keycloak] Expose keycloak generated dns name as env variable (#68)

charts/keycloak/Chart.yaml, charts/keycloak/templates/configmap-sh.yaml, charts/keycloak/templates/statefulset.yaml
Drops setting the system property in favor of setting the
BIND environment variable which was added in
https://github.com/jboss-dockerfiles/keycloak/pull/151.
This does away with a duplicate entry of the system property
'-Djboss.bind.address' in the commandline.
=> [keycloak] Fix bind address handling

charts/keycloak/Chart.yaml, charts/keycloak/templates/configmap-sh.yaml, charts/keycloak/templates/statefulset.yaml
The bind address changes had been done in order to remove a warning from the logs which comes from WildFly but isn't really relevant for Keycloak. However, the change resulted in port-forwarding no longer to be possible. 
We were trying to set the `BIND` environment variable to `0.0.0.0` and the local IP so that port-forwarding should still possible and clustering would continue working. The `docker-entrypoint.sh` scripts suggests this is supported adding the same system property multiple times (https://github.com/jboss-dockerfiles/keycloak/pull/156). However, this is not supported in Java. The last one wins. The script is buggy here.
Fixes: #76
=> [keycloak] Revert bind address changes

charts/keycloak/Chart.yaml, charts/keycloak/templates/ingress.yaml
they should be quoted to avoid issues on wildcard characters
actually we have issue with our wildcard chars: error parsing template.yml: error converting YAML to JSON: yaml: line 29: did not find expected alphabetic or numeric character
current output
```
spec:
tls:
- hosts:
- *.development.example.com
```
desired output
```
spec:
tls:
- hosts:
- '*.development.example.com'
```
=> tls hosts should be quoted

charts/mailhog/Chart.yaml, charts/mailhog/README.md, charts/mailhog/templates/deployment.yaml, charts/mailhog/values.yaml
Making the security context configurable makes mailhog able to run on Openshift, where the security context gets applied automatically (and actually throws errors like these: `1000 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1003220000, 1003229999]]`)
The default values are unchanged as to not break existing deployments.
=> Make securityContext configurable for mailhog

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/ci/postgres-ha-values.yaml, charts/keycloak/requirements.lock, charts/keycloak/requirements.yaml, charts/keycloak/templates/NOTES.txt, charts/keycloak/templates/_helpers.tpl, charts/keycloak/templates/service-headless.yaml, charts/keycloak/templates/service-http.yaml, charts/keycloak/templates/statefulset.yaml, charts/keycloak/templates/test/configmap-test.yaml, charts/keycloak/templates/test/pod-test.yaml, charts/keycloak/values.yaml
This PR collects a number of changes for a new major chart release.
Fixes: #113 
Fixes: #115 
Fixes: #121
=> [keycloak] Create new major release

charts/keycloak/Chart.yaml
apiVersion field is a mandatory for Charts.yaml file [1]
Helm v2.15 and v3 now validates apiVersion and it should be v1
[1]. https://helm.sh/docs/developing_charts/#the-chart-yaml-file
Signed-off-by: Sergiy Kulanov <sergey@kulanov.org.ua>
=> [keycloak] Add apiVersion field

charts/keycloak/Chart.yaml, charts/keycloak/ci/postgres-ha-values.yaml, charts/keycloak/templates/statefulset.yaml
Due to the fact that annotation values are templated
quoting got lost. This fixes the issue.
=> [keycloak] Quote annotations

charts/keycloak/Chart.yaml, charts/keycloak/README.md
That's reopened PR: https://github.com/codecentric/helm-charts/pull/155
I had to close the previous one because I did it under my personal account.
Some time ago (I honestly don't know when), `PROXY_ADDRESS_FORWARDING` was removed from the default environment variables but wasn't removed from default values in the README. This fix resolves the mismatch.
=> [keycloak] Fix misleading information in README

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/prometheusrules.yaml, charts/keycloak/templates/service-headless.yaml, charts/keycloak/templates/service-http.yaml, charts/keycloak/templates/servicemonitor.yaml, charts/keycloak/values.yaml
Adds prometheus operator support for plugins such as https://github.com/aerogear/keycloak-metrics-spi
=> [keycloak] Add Prometheus Operator support

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/_helpers.tpl, charts/keycloak/templates/secret-db.yaml, charts/keycloak/values.yaml
Currently, only `DB_PASSWORD` can be loaded from a Secret, but not `DB_USER`.
We are using an operator pattern for db credential provisioning (think Hashicorp Vault) - and having a static username is not compatible with this pattern, since you are creating and deleting database roles as consuming pods go up and down.
This PR adds support for (optionally) reading the DB user from a secret.
The previous implementation used a variable named `keycloak.persistence.existingSecretKey` - which makes sense as long as you are only reading one value from the Secret. 
By adding another value to read from the Secret, this naming scheme is rendered unclear, so  `keycloak.persistence.existingSecretKey` becomes `keycloak.persistence.existingSecretPasswordKey` - which breaks backwards-compatibility, thus …
=> [keycloak] Add support for reading DB_USER from a k8s Secret

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/statefulset.yaml, charts/keycloak/values.yaml
Adds a configurable `podManagementPolicy` value to the statefulset. The default value is set to `Parallel` to avoid breaking changes as a change to this value on an existing stateful set would fail.
When scaling up Keycloak by adding N+1 to the number of replicas, we see some nodes announce themselves with a UUID as indicated by this log:
```cli
20:35:03,941 INFO  [org.infinispan.CLUSTER] (MSC service thread 1-2) ISPN000094: Received new cluster view for channel ejb: [keycloak-0|3] (4) [keycloak-0, fd524605-7bc5-a6a4-ea6f-4604d418cb32, 35f6bdae-df5c-93e9-ead6-7f14873d346f, keycloak-1]
```
The new nodes will eventually be terminated and cluster will form without the UUID after there is N+1 restarts to the nodes. These are the logs that are output prior to restart:
```
20:40:59,531 WARN …
```
=> [keycloak] Make pod management policy configurable

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/statefulset.yaml, charts/keycloak/values.yaml
Signed-off-by: André Bauer <monotek23@gmail.com>
* update keycloak image to 9.0.0
* introduced proxyAddressForwarding variable (removes it from extraEnv as using additional extraenv requires you to add the variable again to your list or its not merged)
* introduced javaToolOptions variable (defaults to "-XX:+UseContainerSupport -XX:MaxRAMPercentage=50" instead of using static memory config)
* fixed values of readiness & liveness probes in the readme
fixes: https://github.com/codecentric/helm-charts/issues/181
=> [keycloak] Update to 9.0.0 and add additional configuration

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/service-http.yaml
Keycloak service annotation update. Values are now passed through the `tpl` function.
=> [keycloak] Allow templating for service annotation values

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/values.yaml
This fixes a permission issue [1] in the container image which prevented it
from running correctly on OpenShift.
[1] https://github.com/keycloak/keycloak-containers/pull/259
=> [keycloak] Upgrade to 9.0.2

charts/mailhog/Chart.yaml, charts/mailhog/templates/ingress.yaml
This PR switches `mailhog`'s Ingress `apiVersion` to `networking.k8s.io/v1beta1`
In [1.18 Kubernetes `extensions/v1beta1` for Ingress is disabled completely](https://github.com/kubernetes/kubernetes/blob/0f1a27bceeca8f1d37cd69f33d642e38ab414192/CHANGELOG/CHANGELOG-1.18.md#kube-apiserver-1).
=> [mailhog] Use networking.k8s.io/v1beta1 API for Ingress

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/statefulset.yaml, charts/keycloak/values.yaml
We make use of custom annotations for our release process automation; this adds support for annotations to the statefulset 
Signed-off-by: Diego Rodriguez <drodriguez@opengov.com>
=> [keycloak] Add support for adding annotations to the StatefulSet

charts/jenkins/Chart.yaml, charts/jenkins/templates/deployment.yaml
Hi there,
we are running a kubernetes cluster behind a proxy and then the init container can't pull plugins after the deployment. To enable the init container to pull stuff from outside i reuse the extraEnv vars for the init container too. 
The second patch sets the revisionHistory limit for the deployment. Sometimes we have the need to configure more or less than the default of 10 old sets.
Regards
Sascha
=> [jenkins] Add environment variables to the init container and set revisonHistoryLimit

charts/keycloak/Chart.yaml, charts/keycloak/values.yaml
This reverts the changed liveness probe back to the previous
one because the management port by default binds to 127.0.0.1
and, thus, is not available. This is something a user should
actively reconfigure. Also, using WildFly health endpoints
didn't really add any value.
Fixes: #266
=> [keycloak] Revert liveness probe

charts/keycloak/README.md
=> [keycloak] Fix incorrect service monitor path in readme

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/hpa.yaml, charts/keycloak/templates/statefulset.yaml, charts/keycloak/values.schema.json, charts/keycloak/values.yaml
We've been implementing autoscaling for our Keycloak environment as well as switching to KUBE_PING after having issues with scaling and DNS_PING. Here are the changes we had to make to get it working.
Previous experiments with autoscaling keycloak did not go well but the scaling policies in Kubernetes 1.18 as well as KUBE_PING seem to be the answer :smile: 
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-configurable-scaling-behavior
=> [keycloak] Add autoscaling support and KUBE_PING documentation

charts/mailhog/Chart.yaml, charts/mailhog/templates/auth-secret.yaml, charts/mailhog/templates/deployment.yaml, charts/mailhog/templates/ingress.yaml, charts/mailhog/templates/service.yaml
Description of the change
This PR adds .Release.Namespace to objects meta for Mailhog chart.
Benefits
Ability to use the helm chart when having declarative definition of all cluster objects rendered using helm template, for example in tools like Spinnaker.
Possible drawbacks
I don't see any, it will work as previously for helm install.
Signed-off-by: Bartosz Kondek <b.kondek@piwik.pro>
=> [mailhog] Introduce `.Release.Namespace` in objects meta

charts/keycloak/Chart.yaml, charts/keycloak/templates/ingress.yaml
Currently, the helm chart fails when ingress is enabled. This pull request adapts ingress.yaml to ingress v1 syntax. Might be a good idea to add ingress deployment to automated testing.
=> [keycloak] Fix ingress

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/service-http.yaml, charts/keycloak/values.schema.json, charts/keycloak/values.yaml
When creating Service with type of LoadBalancer it results with Security
Group (or equivalent) open to 0.0.0.0/0. By allowing to define
`loadBalancerSourceRanges` one can limit that to a list of allowed
CIDRs. This is a must when a cloud policy of an organisation doesn't
allow opening security groups to 0.0.0.0/0.
=> [keycloak] Allow setting loadBalancerSourceRanges on the svc

charts/keycloak/Chart.yaml, charts/keycloak/templates/_helpers.tpl, charts/keycloak/templates/ingress.yaml
Checking only `.Capabilities.APIVersions.Has "networking.k8s.io/v1"` was not sufficiënt. Improved by checking `.Capabilities.APIVersions.Has "networking.k8s.io/v1/ingress"`.
The `backend` parts is also changed in v1, this is fixed now.
=> [keycloak] fix: networking.k8s.io/v1/ingress check

charts/mailhog/Chart.yaml, charts/mailhog/README.md, charts/mailhog/templates/deployment.yaml, charts/mailhog/values.yaml
Due to this whole Docker quota drama we are mirroring all images to private registry, so we need this setting configurable.
Signed-off-by: Konstanty Karagiorgis <k.karagiorgis@piwik.pro>
=> [mailhog] Add imagePullSecrets to chart

charts/keycloak/Chart.yaml, charts/keycloak/templates/_helpers.tpl, charts/keycloak/templates/ingress.yaml
The fix introduced in #357 uses a lowercase check for the Ingress API `networking.k8s.io/v1/ingress` rather than `networking.k8s.io/v1/Ingress` which fails with a cluster version v1.19.3 like the one in the latest Docker Desktop.
This PR fixes that.
=> [keycloak] fix networking.k8s.io/v1/Ingress API support

charts/keycloak/Chart.yaml, charts/keycloak/templates/service-http.yaml
Similarly to Ingress-Nginx
(https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/templates/controller-service.yaml#L40-L48)
allow to set NodePort when Service of type LoadBalancer is used.
The use case for this is to allow using specific node port when Network
Load Balancer is used in AWS setup and a specific port needs to be used
for a case where security groups need to be managed outside of
Kubernets.
=> [keycloak] Allow NodePort with LoadBalancer

charts/keycloak/Chart.yaml, charts/keycloak/templates/_helpers.tpl
At the moment, the `app.kubernetes.io/version` label is always set to `.Chart.AppVersion`.
However, the keycloak app version string could also be overridden via `.Values.image.tag`. When this happens, the `app.kubernetes.io/version` will show an incorrect version string. This patch will update __helpers.tpl_ and allow it to also accept `.Values.image.tag` as the app version string if it is defined.
=> [keycloak] Allow overriding app version label

charts/keycloak/Chart.yaml, charts/keycloak/templates/rbac.yaml
Even though we may not need to specify custom labels for RBAC resources, the `Role` and `RoleBinding` resource should still contain `keycloak.labels` like other resources created by this Helm chart
=> [keycloak] RBAC resource should include labels

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/ingress.yaml, charts/keycloak/values.yaml
Add ingress.console part to create specific ingress for admin console access. This allow to have specific annotations for /auth/admin access such as `nginx.ingress.kubernetes.io/whitelist-source-range`
Signed-off-by: Olivier Boudet <o.boudet@gmail.com>
=> [keycloak] Add ingress.console (#335)

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/service-http.yaml, charts/keycloak/values.yaml
This PR allows the deployment to explicitly set the externalTrafficPolicy when deploying a service type 'LoadBalancer', allowing the default value of Cluster to be changed to Local as part of the chart provisioning of the load balanced service.
=> [keycloak] Adding externalTrafficPolicy to service definitions

charts/mailhog/Chart.yaml, charts/mailhog/templates/_helpers.tpl, charts/mailhog/templates/deployment.yaml, charts/mailhog/templates/smtp-secret.yaml, charts/mailhog/values.yaml
Add config to add permanent outgoing-smtp config using a secret analogue to the auth secret.
=> [mailhog] Add Outgoing SMTP config

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/statefulset.yaml, charts/keycloak/values.yaml
Since Keycloak takes a significant amount of time to start up, it is helpful to have startupProbe to find out when it's ready to receive connections.
=> [keycloak] Add startupProbe

charts/keycloak/Chart.yaml, charts/keycloak/values.yaml
Greetings codecentric,
I was trying to use your Keycloak charts with minikube and I got this error. After looking why this chart was failing I found out that the pgchecker assigned resources were too low. Also you can use a custom values.yml file to fix this but I think It will be better if the Keycloak chart has this covered from its default values.
Steps to reproduce:
- `helm install keycoak codecentric/keycloak`
- `kubectl describe pod keycloak-0`
```
Events:
Type     Reason     Age                From               Message
----     ------     ----               ----               -------
Normal   Scheduled  82s                default-scheduler  Successfully assigned default/keycloak-0 to minikube
Warning  Failed     76s                kubelet            Error: failed to start …
```
=> [keycloak] increase pgchecker resources

charts/keycloak/Chart.yaml, charts/keycloak/templates/networkpolicy.yaml
Network policies operate on the pod level, not the service. 
Allowing (previous default) port 80 from service doesn't work, since container listens on 8080.
(Since the container port isn't configurable in the values.yaml, I also hardcoded those in the netpol template.)
=> [keycloak] Fix container ports in network policy

charts/mailhog/Chart.yaml, charts/mailhog/README.md, charts/mailhog/templates/_helpers.tpl, charts/mailhog/templates/ingress.yaml, charts/mailhog/values.yaml
This PR adds support Ingress in ApiVersion networking.k8s.io/v1 as networking.k8s.io/v1beta1 is now deprecated. Ports PRs #334  #357 #360 and #450 to the Mailhog chart.
=> [mailhog] add support for ingress v1

charts/mailhog/Chart.yaml, charts/mailhog/README.md, charts/mailhog/templates/ingress.yaml, charts/mailhog/values.yaml
ingressClassName is the preferred way to associated Ingress resources with their controller, the annotation is deprecated (https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation)
the annotation should still be respected by ingress controllers (https://pkg.go.dev/k8s.io/api/networking/v1#IngressSpec: "IngressClassName is the name of the IngressClass cluster resource. The associated IngressClass defines which controller will implement the resource. This replaces the deprecated `kubernetes.io/ingress.class` annotation. For backwards compatibility, when that annotation is set, it must be given precedence over this field...")
=> [mailhog] support ingressClassName on ingress

charts/keycloak/Chart.yaml, charts/keycloak/templates/_helpers.tpl, charts/keycloak/templates/route.yaml
We use sha256 image tags which are longer then allowed label length and caused a deployment error:
```
Invalid value: "52771198613a47a3c3a617937c137a61aa6591267ba6ee03f63ff04b61d5f3f8": must be no more than 63 characters
```
truncate the label after 63 characters.
=> [keycloak] fix uncut version label

charts/keycloak/Chart.lock, charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/requirements.yaml
It fixes the problem of https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/Chart.yaml#L1 is apiV1 and the Postgres dependency is already apiV2.
Closes #465
=> [keycloak] feat: support helm chart version 2

charts/keycloak/Chart.yaml, charts/keycloak/templates/_helpers.tpl, charts/keycloak/templates/ingress.yaml
Fix #496
Alternative to #499 => do not make the api version configurable, but retrieve it correctly.
I changed the logic for both charts => not yet fully tested!
=> [keycloak] Change Ingress Api Version Logic

charts/keycloak/Chart.yaml, charts/keycloak/templates/NOTES.txt
The Keycloak ingress uses the `tpl` function for `rules.host` and `tls.hosts` which allows us to define a single value for the Keycloak host:
```
myHostValue: "login.example.org"
ingress:
rules:
- host: "{{ .Values.myHostValue }}"
tls:
- hosts:
- "{{ .Values.myHostValue }}"
```
Right now, the NOTES.txt does not use the `tpl` function and therefore prints the plain expression:
>  Keycloak was installed with an Ingress and an be reached at the following URL(s):
>
>  - https://{{ .Values.myHostValue }}/
This PR introduces the `tpl` function in NOTES.txt to print the actual host value.
=> [keycloak] Use tpl for ingress hosts in NOTES.txt

charts/keycloak/Chart.yaml, charts/keycloak/templates/secrets.yaml
Fixes #504 'invalid Yaml document separator' error when there is more than one secret declared in keycloak chart values
Signed-off-by: Hervé Le Meur <hlemeur@cloudbees.com>
=> [keycloak] put secrets separator at the top of their definition

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/statefulset.yaml, charts/keycloak/values.yaml
Hi guys,
This PR adds a non-default option to skip any initContainers when deploying the keycloak statefulset. 
Why?
Because when using a service mesh whose connectivity relies on a sidecar (like Istio's envoy-proxy), an initContainer which requires network connectivity will never complete.
Cheers!
D
=> [keycloak] Add option to skip init containers

charts/keycloak/Chart.yaml, charts/keycloak/templates/secrets.yaml
My previous PR [#505](https://github.com/codecentric/helm-charts/pull/505) introduced an error as multiple secrets defined in one file weren't separated anymore by '---', so my fix of putting the separator at the top of the secret template wasn't enought.
The correct fix is to remove the trimming on the right side of the range. (Pass the lint too)
Signed-off-by: Hervé Le Meur <hlemeur@cloudbees.com>
=> [keycloak] fix: correct way of fixing separator lint issue #504

charts/keycloak/Chart.yaml
=> [keycloak] Update minor Keycloak version to 15.1.1

charts/keycloak/Chart.yaml, charts/keycloak/README.md
=> [keycloak] Major Keycloak Update to version 16.1.1

charts/keycloak/README.md
* Cluster upgrade failed during testing of a 3 node cluster from the 9.5.0 chart to 10.3.1, the first upgraded keycloak pod failed to parse some infinispan messages.
* Updated section to include same guidance as other incompatible
upgrades.
=> [keycloak] chore: Update Keycloak readme with respect to <10.x upgrade 

charts/keycloak/templates/NOTES.txt, charts/keycloak/templates/ingress.yaml
Fix for issue #522 : Allow to deploy ingress without host specified
=> [keycloak] Fix #522 : allow to deploy ingress without host specified

charts/mailhog/templates/ingress.yaml
Signed-off-by: Ashley Cambrell <acambrell@gmail.com>
=> [mailhog] Incorrect YAML syntax when Ingress labels are used

charts/mailhog/templates/deployment.yaml
now:
when outgoingSMTP.enabled and auth.enabled the SMTP volume write to the root volumes key
fix:
make the volume key either or and add to the array of volume to support either or both
log:
```
➜ ~ k logs -f -n $n $p
2022/02/02 05:32:58 Using in-memory storage
[HTTP] Error reading auth-file: open /authdir/auth.txt: no such file or directory
```
=> [mailhog] fix: auth volume overwritten when outgoingSMTP.enabled

charts/keycloak/templates/poddisruptionbudget.yaml
Policy/v1beta1 is deprecated in Kubernetes since version 1.21.
The PR will adapt PodDisruptionBudget API version in Keycloak based on Kubernetes version.
=> Use policy/v1 api for PDB in K8s ver 1.21+

charts/mailhog/README.md, charts/mailhog/templates/deployment.yaml, charts/mailhog/values.yaml
Added possibility to set priorityClassName.
Signed-off-by: Błażej Frydlewicz <b.frydlewicz@piwik.pro>
=> Introduced priorityClassName

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/values.yaml
=> [keycloak] Major Keycloak Update to version 17.0.1

charts/keycloakx/Chart.yaml
=> [keycloakx] Major Keycloak.X Update to version 17.0.1

.github/workflows/release-charts.yaml
=> Adapt release workflow to support keycloakx chart

.gitignore, charts/keycloakx/README.md, charts/keycloakx/examples/postgresql-kubeping/Dockerfile, charts/keycloakx/examples/postgresql-kubeping/cache-ispn-kubeping.xml, charts/keycloakx/examples/postgresql-kubeping/keycloak-db-values.yaml, charts/keycloakx/examples/postgresql-kubeping/keycloak-server-values.yaml, charts/keycloakx/examples/postgresql-kubeping/readme.md, charts/keycloakx/examples/postgresql/readme.md, charts/keycloakx/examples/readme.md, charts/keycloakx/templates/serviceaccount.yaml, charts/keycloakx/values.schema.json, charts/keycloakx/values.yaml
- Added support for allowing the Keycloak service-account to read
pod information required for kube_ping
- Added an example for using jgroups with kube_ping
Fixes #568
=> [keycloakx] feature: Add support for kube_ping clustering

charts/keycloakx/Chart.yaml, charts/keycloakx/README.md, charts/keycloakx/examples/postgresql-kubeping/Dockerfile, charts/keycloakx/examples/postgresql-kubeping/readme.md, charts/keycloakx/templates/statefulset.yaml, charts/keycloakx/values.schema.json, charts/keycloakx/values.yaml
=> [keycloakx] Major version upgrade to Keycloak 18.0.0 (#591)

charts/keycloak/Chart.lock, charts/keycloak/Chart.yaml
Bitnami did some cleanup and removed old chart versions. Bumped it to the latest available version with the old appVersion, should not change anything.
Signed-off-by: Frederik Grieshaber <freddy.grieshaber+github@gmail.com>
=> Increase postgresql dependency chart version

charts/keycloak/templates/poddisruptionbudget.yaml
`{{- if semverCompare ">=1.21.0" .Capabilities.KubeVersion.GitVersion }}` in PodDisruptionBudget template file (keycloak) does not work when Kubernetes gitversion uses pre-release notation (vX.Y.Z-pre.number for example), which is the case for GKE clusters.
This PR bases API selection on  `.Capabilities.APIVersions.Has` function.
Fixes https://github.com/codecentric/helm-charts/issues/607
Signed-off-by: Didier Hamels <didier.hamels@gmail.com>
=> [keycloak] fix PodDisruption API selection

charts/keycloak/templates/NOTES.txt
Fix typo for Ingress message
Signed-off-by: Matheus Palu <72210801+mpalu@users.noreply.github.com>
=> [keycloak] update NOTES.txt

charts/keycloak/templates/_helpers.tpl
While testing the replication setup in postgresql with keycloak I found a bug in the chart that will occur in the `pgchecker` `initContainer` while waiting for the postgresql server to be up and running.
Indeed when using `postgresql.primary.fullname` we ended up having  `keycloak.postgresql.fullname` being set to `RELEASE-NAME-postgresql-primary` because of these [lines](https://github.com/bitnami/charts/blob/e34ee5c5aeafabe15cbf0d2b0fecb18483bc6415/bitnami/postgresql/templates/_helpers.tpl#L17-L18). Therefore the `pgchecker` container would never resolve `RELEASE-NAME-postgresql-primary` because no such service is deployed while using postgresql replication setup and just be stuck on `Init:0/1` because of hanging `nc -z -w 2 keycloak-postgresql-primary 5432` DB server check command.
I …
=> [keycloak] fix(_helpers.tpl): redefine `keycloak.postgresql.fullname` to use postgresql replication setup

charts/keycloakx/README.md, charts/keycloakx/values.schema.json
Improve the documentation reagarding the newly feature to use an existing secret for db connections #601 
Signed-off-by: Frederik Grieshaber <freddy.grieshaber+github@gmail.com>
=> [keycloakx] improve documentation for existing secret

charts/keycloakx/templates/_helpers.tpl
Followup of: #601 
The previous setup resulted in the `name` missing when no existingSecret is provided:
```yaml
name: KC_DB_PASSWORD
valueFrom:
secretKeyRef:
key: password
```
Since `{{- if .Values.database.existingSecret }}` is then false and the whole thing is skipped.
=> fix: correct fallback when no existingSecret

charts/mailhog/README.md, charts/mailhog/templates/deployment.yaml, charts/mailhog/values.yaml
- Sets mailhog `spec.replicas` value, allows override via helm values
- Upstream update to `5.0.7`
- Uses `podReplicas` instead of `replicaCount` to match existing `podXYZ` variables
PR based on https://github.com/codecentric/helm-charts/pull/206 , credits to @bartlettt
=> feature: Allow setting mailhog replicas

charts/mailhog/README.md, charts/mailhog/templates/deployment.yaml, charts/mailhog/templates/service.yaml, charts/mailhog/values.yaml
When deploying the mailhog graph using ingress GCE the health check of Google's Load Balancer fails to succeed if the service is configured with basic auth.
This is because the health check is not able to set authentication parameters so that a request gets a return code of 200.
Also, even though there is an smtp port, the load balancer health check only has the ability to communicate via HTTP, HTTPS and HTTP2 protocol.
Reference: https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#direct_health
Therefore, the purpose of this change is to give the ability to add an extra container to be used only as a route for the Load Balancer life check to work, at the same time that mailhog basic authentication is enabled.
Signed-off-by: Julliano Goncalves <jullianow@gmail.com>
=> [mailhog] Add extraPorts in Service and extraContainers in Deployment

charts/mailhog/README.md, charts/mailhog/templates/deployment.yaml, charts/mailhog/values.yaml
In some use cases we need to have more control over the liveness probes on standby so that the container is available at the right time.
Also, in some cases, probes that vary the process in a short time, can produce many logs that we do not necessarily want.
Therefore, this change in the ability to set all existing properties to more precisely control with the liveliness and readiness probes should behave.
> **Note**
>
>All default values ​​are based on the documentation and what was already in use by the chart.
Signed-off-by: Julliano Goncalves <jullianow@gmail.com>
=> [mailhog] Add ability to precisely control liveness and readiness probes

charts/keycloakx/templates/statefulset.yaml
=> [keycloakx] Don't trim the relative path when the path is just "/"

charts/keycloak/templates/_helpers.tpl, charts/keycloak/values.schema.json, charts/keycloakx/templates/_helpers.tpl, charts/keycloakx/values.schema.json
This PR adds `integer` as an valid input type for `image.tag` in keycloak and keycloakx chart.
Resolves #639
=> [keycloak] [keycloakx] feat: Add integer to valid image tag type

charts/keycloakx/templates/_helpers.tpl, charts/keycloakx/values.yaml
Add the ability to specify the database secret key to a value other than 'password':
The vault will still default to 'password' with this pr, but enables extensibility of the chart.
=> [keycloakx] Feat: Database key parameter add

charts/mailhog/README.md
Pod affinity is provided in the `values.yaml` but it is not mentioned in the `README.md`.
This commit adds the key to the Helm Chart values table in the README.
Signed-off-by: Rishikesh Nair <42700059+rishinair11@users.noreply.github.com>
=> [mailhog]: Add affinity configuration in README

charts/keycloakx/Chart.yaml, charts/keycloakx/examples/postgresql-kubeping/Dockerfile, charts/keycloakx/values.yaml
I've updated the Keycloak container image to version 19.0.3.
=> [keycloakx] Bump Keycloak to v19.0.3

charts/keycloakx/README.md
Since #621 was merged this doesn't reference anything:
> Please refer to the section on database configuration for how to configure a secret for this.
Also the environment variables look wrong to me (edit: not only me #605)? From the docs:
> use the KEYCLOAK_ADMIN and KEYCLOAK_ADMIN_PASSWORD environment variables to create an initial admin account.
>
> -- https://www.keycloak.org/docs/latest/server_admin/#creating-the-account-remotely
So here my attribution to the docs, feedback is of course welcome :)
=> docs: updates keycloakx readme about creating the admin user

charts/keycloakx/templates/service-http.yaml, charts/keycloakx/templates/statefulset.yaml
The https service and https containerports are typically not needed as most implementations will use the ingress with http backend communication. The https ports should therefore be disabled by default and not included in the service and statefulset. Only if someone manually sets a https port number via values, it should be exposed.
This also fixes some default prometheusrules which alert if service endpoints are not available.
=> feat: only expose https ports when https port is defined in the service

charts/keycloak/values.yaml
Hey!
I tried installing the helm chart with my values, I am advanced with helm, so I created my own values and ingress configuration, when I installed, I have noticed I encounter the error of:
```bash
Error syncing to GCP: error running load balancer syncing routine: error getting secrets for Ingress: secret "" does not exist
```
I never encountered this error so when googling I saw it is because I am using the GCE annotation in my ingress
```yaml
annotations:
networking.gke.io/managed-certificates: my-managed-certificate
kubernetes.io/ingress.class: "gce"
```
and the tls configuration in the ingress:
```yaml
tls:
- hosts:
- keycloak.example.com
secretName: ""
```
got deployed to my ingress.
This PR will fix it as setting a tls config is not mandatory and there is other reasons to …
=> comment ingress tls example to avoid conflicts

charts/keycloakx/templates/hpa.yaml, charts/keycloakx/values.yaml
The keycloakx chart is still using `autoscaling/v2beta2` for the HPA when autoscaling is enabled.
`autoscaling/v2beta2` has been deprecated since v1.23, and all k8s versions <= v1.23 are EOL.
I didn't make a PR to update the HPA API in the keycloak chart since it might make sense for that to remain on the legacy version. But I will make one if deemed appropriate.
=> Update deprecated autoscaling/v2beta2 api

charts/keycloakx/Chart.yaml, charts/keycloakx/examples/postgresql-kubeping/Dockerfile, charts/keycloakx/values.yaml
Keep the [upgrading guide](https://www.keycloak.org/docs/21.1.1/upgrading/index.html) in mind.
=> [keycloakx] Bump Keycloak to v21.1.1

charts/keycloakx/.bumpversion.cfg, charts/keycloakx/Chart.yaml
=> Bump keycloakx chart version: 2.2.2 → 2.3.0

charts/keycloakx/Chart.yaml, charts/keycloakx/README.md, charts/keycloakx/ci/h2-values.yaml, charts/keycloakx/examples/postgresql-kubeping/Dockerfile, charts/keycloakx/examples/postgresql-kubeping/keycloak-server-values.yaml, charts/keycloakx/examples/postgresql/keycloak-server-values.yaml, charts/keycloakx/templates/statefulset.yaml, charts/keycloakx/values.yaml
Upgraded to version 25.0.0 of Keycloak. Tested in separate systems, and only change needed was to use the new internal 9000 port for health checks and metrics.
=> Upgraded to version 25.0.0 of Keycloak

charts/keycloakx/README.md
Enable IPv6 dualstack support by default since Keycloak v22. https://www.keycloak.org/server/configuration-production#_configure_keycloak_server_with_ipv4_or_ipv6
=> Remove Keycloakx parameter preferIPv4Stack

charts/keycloakx/README.md, charts/keycloakx/ci/h2-values.yaml, charts/keycloakx/examples/postgresql-kubeping/keycloak-server-values.yaml, charts/keycloakx/examples/postgresql/keycloak-server-values.yaml
The parameter `-XX:+UseContainerSupport` is no longer required for Keycloak >= v21 based on JDK v17. JDK >= v17 has enabled the container support by default.
=> Remove Keycloak JDK UseContainerSupport parameter

charts/keycloakx/README.md, charts/keycloakx/ci/h2-values.yaml, charts/keycloakx/examples/postgresql-kubeping/keycloak-server-values.yaml, charts/keycloakx/examples/postgresql/keycloak-server-values.yaml
There is a a lot of evidence that the parameter is set to `java.awt.headless=true` in Quarkus by default.
* Quarkus Building native Images: https://quarkus.io/guides/building-native-image) see default value for `java.awt.headless`
* https://github.com/quarkusio/quarkus/issues/20565
* https://github.com/quarkusio/quarkus/pull/20850
=> Remove the JDK parameter java.awt.headless=true

charts/keycloakx/templates/servicemonitor.yaml
Fix issue with servicemonitor trying to read .Values within a loop
Reproduction before fix
```sh
❯ helm template --set extraServiceMonitor.enabled=true ./
Error: template: keycloakx/templates/servicemonitor.yaml:37:24: executing "keycloakx/templates/servicemonitor.yaml" at <.Values.http.internalScheme>: nil pointer evaluating interface {}.http
```
=> Fix servicemonitor http endpoint

ct.yaml
It seems like the old keycloak chart can't be built due to some changes in the bitnami Repository. I think the old charts can be deprecated. For now we stop linting the other charts 
https://github.com/codecentric/helm-charts/actions/runs/11853000905/job/33032242686
=> just lint the keycloakx chart

.github/workflows/release-charts.yaml, README.md, charts/keycloak/README.md, charts/keycloakx/README.md, charts/mailhog/README.md
Fix : https://github.com/codecentric/helm-charts/issues/797
Charts will now be published in addition to traditional helm deployment also in GitHub container registry to be consumed by OCI client or directly since Helm 3.8
I've tested the release on my fork
This is similar to other OpenSource charts: https://github.com/jenkinsci/helm-charts/pull/1196 or https://github.com/sigstore/helm-charts/pull/43
Hope this contribution will be accepted so that we can proxy/pull such OCI artifact
=> feature: publish to GHCR registry

charts/keycloakx/Chart.yaml, charts/keycloakx/examples/postgresql-kubeping/Dockerfile, charts/keycloakx/values.yaml
There have been several CVE since the version currently in the chart:
https://github.com/keycloak/keycloak/security
Is `microhaug` broken? Previously that would automatically bump the chart
=> feat: bump keycloak to 26.2.3 due CVE

charts/keycloak/templates/_helpers.tpl, charts/keycloakx/templates/_helpers.tpl, charts/mailhog/templates/_helpers.tpl
This commit prevents failing deployment when `.Values.image.tag` (in our case shortened commit hash) is just a number (like `4524551` - contains just decimal digits, without any `a`-`f`)
Resolves #821
=> fix: toString before truncate

charts/keycloakx/Chart.yaml, charts/keycloakx/examples/postgresql-kubeping/Dockerfile, charts/keycloakx/values.yaml
=> Update Keycloak to 26.3.3

charts/keycloakx/README.md, charts/keycloakx/templates/statefulset.yaml
Starting in [Keycloak 26.1.0](https://www.keycloak.org/2025/01/keycloak-2610-released) the default stack has been updated to `jdbc-ping`.  This update to the helm chart updates the default stack settings to reflect this change and updates documentation related to it as well.
You can validate the change is working as expected by connecting to keycloak's backend database and executing this query:
`SELECT * FROM jgroups_ping;`
=> Updated default cache stack and related documentation

charts/keycloakx/Chart.yaml, charts/keycloakx/examples/postgresql-kubeping/Dockerfile, charts/keycloakx/values.yaml
Bumped the version for Keycloak to the most recent and bumped the chart version.
=> Bumped chart and keycloak version
