codecentric/helm-charts

.circleci/kind-config.yaml
=> [CI] Use two worker nodes only

charts/mailhog/.helmignore, charts/mailhog/Chart.yaml, charts/mailhog/README.md, charts/mailhog/templates/_helpers.tpl, charts/mailhog/templates/auth-secret.yaml, charts/mailhog/templates/deployment.yaml, charts/mailhog/templates/ingress.yaml, charts/mailhog/templates/service.yaml, charts/mailhog/values.yaml
=> [mailhog] Update Mailhog chart to latest conventions

charts/keycloak/Chart.yaml, charts/keycloak/OWNERS, charts/keycloak/README.md, charts/keycloak/ci/h2-values.yaml, charts/keycloak/ci/postgres-ha-values.yaml, charts/keycloak/requirements.lock, charts/keycloak/requirements.yaml, charts/keycloak/scripts/datasource.cli, charts/keycloak/scripts/ha.cli, charts/keycloak/scripts/logging.cli, charts/keycloak/scripts/node-identifier.cli, charts/keycloak/scripts/reverse-proxy.cli, charts/keycloak/templates/NOTES.txt, charts/keycloak/templates/_helpers.tpl, charts/keycloak/templates/configmap.yaml, charts/keycloak/templates/db-secret.yaml, charts/keycloak/templates/headless-service.yaml, charts/keycloak/templates/http-service.yaml, charts/keycloak/templates/ingress.yaml, charts/keycloak/templates/keycloak-secret.yaml, charts/keycloak/templates/poddisruptionbudget.yaml, charts/keycloak/templates/statefulset.yaml, charts/keycloak/templates/test/test-configmap.yaml, charts/keycloak/templates/test/test-pod.yaml, charts/keycloak/values.yaml
=> Import Keycloak chart

README.md
=> Remove WIP from readme

charts/jenkins/Chart.yaml, charts/jenkins/README.md
=> [jenkins] Fix version in readme

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/ingress.yaml, charts/keycloak/values.yaml
[keycloak] Add labels to ingress
* Update keycloak ingress template, add labels
* Update README.md, add ingress.labels description
* Bump chart version
* Add default value to values.yaml
Signed-off-by: Tibor Vukovic <tiborvukovic91@gmail.com>
=> [keycloak] Additional labels to ingress

charts/keycloak/Chart.yaml, charts/keycloak/ci/postgres-ha-values.yaml
This is in preparation for possible future upgrade tests.
Auto-generating passwords would break upgrades.
=> [keycloak] Use hard-coded PostgreSQL password for CI

charts/jenkins/Chart.yaml, charts/jenkins/README.md, charts/jenkins/values.yaml
=> [jenkins] Upgrade to 2.164.3

charts/jenkins/Chart.yaml, charts/jenkins/README.md, charts/jenkins/ci/k8s-values.yaml, charts/jenkins/templates/deployment.yaml, charts/jenkins/values.yaml
=> [jenkins] Add option to configure extra volumes and init containers

charts/jenkins/Chart.yaml, charts/jenkins/README.md, charts/jenkins/templates/deployment.yaml
=> [jenkins] Add option to configure defaultMode for reference content

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/statefulset.yaml, charts/keycloak/values.yaml
Here a PR for the issue #54 i made previously
Thanks in advance
Fred
=> [keycloak] Allow to choose restartPolicy

charts/keycloak/Chart.yaml, charts/keycloak/templates/statefulset.yaml, charts/keycloak/values.yaml
=> [keycloak] Make resources for init container configurable

.circleci/install_charts.sh
=> [ci] Upgrade kind to v0.3.0

charts/keycloak/Chart.yaml, charts/keycloak/templates/NOTES.txt
Signed-off-by: shadai.ali <nafiouali@gmail.com>
=> [keycloak] Fix keycloak pods label filtering

charts/keycloak/Chart.yaml, charts/keycloak/templates/statefulset.yaml
Fixes a regression introduces by #72 which caused
clustering to no longer work.
=> [keycloak] Add pod IP to fix clustering

.circleci/install_charts.sh, .circleci/install_tools.sh, .circleci/release.sh, .gitignore
=> [ci] Update tools

index.yaml
The last tooling upgrade messed up 'index.yaml' creation. This manually
fixes the issue. The underlying issue is yet to be fixed.
=> Fix index.yaml

.circleci/install_tools.sh, .circleci/release.sh
=> [ci] Upgrade chart-releaser to v0.2.2

charts/keycloak/Chart.yaml, charts/keycloak/README.md
Fix the outdated external links to change-database-cli files.
Signed-off-by: Roy Hardin <hardin@hardin.io>
=> [keycloak] Update change-database.cli links

charts/jenkins/Chart.yaml, charts/jenkins/README.md
=> [jenkins] Add comparison section

charts/mailhog/Chart.yaml, charts/mailhog/templates/service.yaml
=> [mailhog] Fix service annotations

charts/keycloak/Chart.yaml, charts/keycloak/templates/test/configmap-test.yaml
=> [keycloak] Add missing colon between service name and port

charts/mailhog/Chart.yaml, charts/mailhog/README.md, charts/mailhog/values.yaml
=> [mailhog] Fix default hosts values for Ingress and their description in README

charts/keycloak/Chart.yaml, charts/keycloak/values.yaml
Signed-off-by: gs11 <gustav.sinder@gmail.com>
=> [keycloak] Document name overrides in values file

charts/keycloak/Chart.yaml, charts/keycloak/templates/_helpers.tpl
=> fix(keycloak): Quote release names used in labels

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/values.yaml
Upgrade Keycloak to the latest version.
=> [keycloak] Upgrade Keycloak to 8.0.1

charts/mailhog/Chart.yaml, charts/mailhog/README.md
small update in readme.
looks like the repo was copied and not changed yet and the nodeSelector was duplicate
=> [mailhog] Fix repo and nodeSelector docs

charts/keycloak/Chart.yaml, charts/keycloak/README.md
Signed-off-by: Oscar Löfwenhamn <oscar.lofwenhamn@cgi.com>
=> Add `postgresql.persistence.enabled` entry to README list

charts/keycloak/Chart.yaml, charts/keycloak/README.md
=> [keycloak] Add missing documentation for 'serviceAccount.name'

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/_helpers.tpl, charts/keycloak/templates/servicemonitor.yaml, charts/keycloak/values.yaml
Signed-off-by: Nicolas Laduguie <nicolas.laduguie@dolby.com>
=> [keycloak] Add Prometheus operator serviceMonitor namespace

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/statefulset.yaml, charts/keycloak/values.yaml
Primarily useful for large clusters with a lot of Infinispan cache to rebalance on deployment.
Happy to create an issue for this if required 👌
=> [keycloak] Add parameter to override termination grace period

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/values.yaml
=> [keycloak] Make -XX:MaxRAMPercentage a double value

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/service-http.yaml, charts/keycloak/values.yaml
Signed-off-by: Dieter De Meyer <dieterdemeyer@gmail.com>
=> [keycloak] Added support for setting additional ports to expose via the Service

.circleci/ct.yaml, charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/requirements.lock, charts/keycloak/requirements.yaml, charts/keycloak/templates/_helpers.tpl, charts/keycloak/templates/statefulset.yaml, charts/keycloak/values.yaml
* Keycloak is updated to 10.0.0
* PostgreSQL chart dependency is updated to 8.9.5
Closes: #217
=> [keycloak] Upgrade Keycloak and PostgreSQL

charts/mailhog/Chart.yaml, charts/mailhog/README.md, charts/mailhog/templates/deployment.yaml, charts/mailhog/values.yaml
Signed-off-by: Léo Martinez <leo84.martinez@gmail.com>
=> [mailhog] Add support for extra pod labels

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/ci/postgres-ha-disabled-jgroups-port-values.yaml, charts/keycloak/templates/service-headless.yaml, charts/keycloak/templates/statefulset.yaml, charts/keycloak/values.yaml
=> [keycloak] Add option to disable the JGroups port

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/ingress.yaml, charts/keycloak/values.yaml
=> [keycloak] Make ingress service port configurable

.gitignore, charts/jenkins/Chart.yaml, charts/jenkins/README.md, charts/jenkins/ci/k8s-values.yaml, charts/jenkins/templates/_helpers.tpl, charts/jenkins/templates/deployment.yaml, charts/jenkins/test/test.py, charts/jenkins/values.yaml
=> [jenkins] Upgrade to 2.222.3

.circleci/ct.yaml, .circleci/install_charts.sh, .circleci/install_tools.sh
=> Update CI to Helm 3

.circleci/config.yml
=> Bump chart-testing to v3.0.0-rc.1

charts/keycloak/Chart.yaml, charts/keycloak/templates/ingress.yaml
Add template capabilities on ingress host names.
Eg.:  In order to use `Release.Name` in  host name
=> [keycloak] Add template capabilities on ingress host names

.circleci/release.sh
=> Force-checkout gh-pages during release

.circleci/release.sh
=> Fix release

charts/keycloak/Chart.yaml, charts/keycloak/README.md
=> [keycloak] Fix wrong indentation in docs

charts/keycloak/Chart.yaml, charts/keycloak/values.yaml
=> [keycloak] Fix default value for imagePullSecrets

charts/mailhog/Chart.yaml, charts/mailhog/README.md, charts/mailhog/templates/NOTES.txt, charts/mailhog/templates/deployment.yaml, charts/mailhog/templates/ingress.yaml, charts/mailhog/templates/service.yaml, charts/mailhog/values.yaml
=> [mailhog] Update Mailhog to v1.0.1

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/ingress.yaml, charts/keycloak/values.yaml
=> [keycloak] Make tls secret optional

charts/keycloak/Chart.yaml, charts/keycloak/README.md
=> [keycloak] Correctly quote numbers in environment variables

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/ci/postgres-ha-netpol-values.yaml, charts/keycloak/templates/networkpolicy.yaml, charts/keycloak/templates/statefulset.yaml, charts/keycloak/values.yaml
Allow ingress network policies for keycloak and postgres
=> [keycloak] Add network policies support

charts/keycloak/Chart.yaml, charts/keycloak/README.md
Signed-off-by: Samu Toimela <toimelas@gmail.com>
Fix some formatting and few invalid default values.
=> [keycloak] Update readme

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/servicemonitor.yaml, charts/keycloak/values.yaml
=> [keycloak] Add namespace selector for service monitor

charts/keycloak/Chart.yaml, charts/keycloak/templates/statefulset.yaml
=> [keycloak] Use subPath to mount startup scripts

charts/keycloak/Chart.yaml, charts/keycloak/README.md
=> [keycloak] Add section on running behind reverse proxy

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/servicemonitor.yaml, charts/keycloak/values.schema.json, charts/keycloak/values.yaml
=> [keycloak] Add additional service monitor for Metrics SPI

charts/keycloak/Chart.yaml, charts/keycloak/templates/_helpers.tpl
=> [keycloak] Remove unused helper template

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/service-http.yaml, charts/keycloak/values.schema.json, charts/keycloak/values.yaml
Signed-off-by: Viacheslav Kropotko <vjkropotko@gmail.com>
=> [keycloak] Add Affinity to HTTP Service

charts/keycloak/Chart.yaml, charts/keycloak/templates/rbac.yaml
Resolves #368 
Signed-off-by: Heiko Nickerl <dev@heiko-nickerl.com>
=> [keycloak] Fix installation in numeric namespaces (#368)

charts/keycloak/Chart.yaml, charts/keycloak/templates/rbac.yaml
Resolves #371 
Signed-off-by: Heiko Nickerl <dev@heiko-nickerl.com>
=> [keycloak] Install RBAC in namespace, not cluster-wide

.circleci/release.sh
=> Ignore deleted charts in release script

charts/mailhog/Chart.yaml, charts/mailhog/README.md, charts/mailhog/templates/_helpers.tpl, charts/mailhog/templates/auth-secret.yaml, charts/mailhog/templates/deployment.yaml, charts/mailhog/templates/ingress.yaml, charts/mailhog/templates/service.yaml, charts/mailhog/templates/serviceaccount.yaml, charts/mailhog/values.yaml
* Add ingress labels
* Add service account
* Don't mount service account token by default
* Add container security context and improve default settings
Closes: #353
Closes: #333
=> [mailhog] Add various improvements and require Helm 3

.github/workflows/lint-test.yaml, kind.yaml
=> Add kind config file

charts/keycloak/Chart.yaml, charts/keycloak/templates/test/configmap-test.yaml
=> [keycloak] Upgrade to 11.0.3

charts/keycloak/Chart.yaml, charts/keycloak/values.yaml
recreated from PR https://github.com/codecentric/helm-charts/pull/397
=> [keycloak] Remove unneeded comment from values.yaml

charts/keycloak/Chart.yaml, charts/keycloak/templates/secrets.yaml, charts/keycloak/values.yaml
specify secrets's type.
https://github.com/codecentric/helm-charts/issues/324
=> [keycloak] Apply secret type configured in values file

charts/keycloak/Chart.yaml, charts/keycloak/README.md
Bump chart versions
Fixes #377
=> [keycloak] Upgrade to 12.0.4 (#377)

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/requirements.lock, charts/keycloak/requirements.yaml, charts/keycloak/templates/_helpers.tpl
=> [keycloak] update postgres subchart to 10.3.13

.github/workflows/lint-test.yaml, charts/keycloak/Chart.yaml, charts/keycloak/README.md
Bump chart versions
Fixes #430
=> [keycloak] Upgrade to 13.0.1 (#430)

charts/keycloak/Chart.yaml, charts/keycloak/README.md
Bump chart versions
Update upgrade guide
Fixes #448
=> [keycloak] Upgrade to 14.0.0 (#448)

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/ingress.yaml, charts/keycloak/values.schema.json, charts/keycloak/values.yaml
Signed-off-by: Cedric Oswald <c.oswald@hmstr.de>
(cherry picked from commit 33be3dccad011646dbadea1cc72afe41c18c8df2)
=> [keycloak] Fix #446 by making pathType for ingress rules configurable

charts/keycloak/Chart.yaml, charts/keycloak/templates/NOTES.txt
This is related to #446.
Fixes #451
=> [keycloak] Fix ingress route output (#451)

charts/keycloak/Chart.yaml, charts/keycloak/README.md
Signed-off-by: Timothy Tobin <timtobin52@gmail.com>
=> [keycloak] Upgrade to Keycloak 15.0.2

charts/keycloak/Chart.yaml
- No functional changes
- Fixed a commit message
=> [keycloak] Release new chart version 15.0.1

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/statefulset.yaml, charts/keycloak/values.yaml
Adds support to define a templated topologySpreadConstraints field.
=> [keycloak] support for topologySpreadConstraints

charts/keycloak/Chart.yaml, charts/keycloak/README.md, charts/keycloak/templates/ingress.yaml, charts/keycloak/values.yaml
Add support for ingressClassName
=> [keycloak] Add support for ingressClassName

charts/mailhog/Chart.yaml, charts/mailhog/templates/_helpers.tpl, charts/mailhog/templates/ingress.yaml
=> [mailhog] Change Ingress Api Version Logic

charts/keycloak/values.yaml
Fixes #517
It took me 5 mins to open this PR, using the online editor.
=> [keycloak] comment explaning image tag & appVersion

charts/keycloakx/README.md, charts/keycloakx/examples/postgresql/readme.md
=> [keycloakx] Revise start command in readme

charts/keycloakx/templates/statefulset.yaml, charts/keycloakx/values.yaml
=> [keycloakx] Fix typo in KC_DB_URL_DATABASE environment variable

charts/keycloakx/templates/statefulset.yaml
Signed-off-by: bovy89 <bovy89@gmail.com>
=> improve command and args management in order to avoid an empty array if not needed

charts/keycloakx/templates/statefulset.yaml
=> [keycloakx] Health check depens on health.enabled

charts/keycloakx/templates/poddisruptionbudget.yaml
Signed-off-by: bovy89 <bovy89@gmail.com>
Use policy/v1 if supported
=> use PDB policy/v1 if supported  (resolve issue #622)

charts/keycloakx/Chart.yaml, charts/keycloakx/examples/postgresql-kubeping/Dockerfile, charts/keycloakx/values.yaml
It's time to get renovate running. :wink:
=> [keycloakx] Bump Keycloak to version 20.0.3

charts/mailhog/.bumpversion.cfg, charts/mailhog/Chart.yaml
Signed-off-by: Julliano Goncalves <jullianow@gmail.com>
=> Bump mailhog chart version: 5.2.2 -> 5.2.3

charts/keycloakx/templates/servicemonitor.yaml
fix the rendering of the internal port in the serviceMonitor
=> FIX: rendering of the internal port in the serviceMonitor

charts/keycloak/templates/_helpers.tpl, charts/keycloakx/templates/_helpers.tpl, charts/mailhog/templates/_helpers.tpl
Fix https://github.com/codecentric/helm-charts/issues/802
=> fix: add truncate filter on version label

charts/keycloakx/Chart.yaml, charts/keycloakx/examples/postgresql-kubeping/Dockerfile, charts/keycloakx/values.yaml
=> Upgrade Keycloak to 26.0.7

charts/keycloakx/examples/cloudnative-pg/keycloak-cluster.yaml, charts/keycloakx/examples/cloudnative-pg/keycloak-server-values.yaml, charts/keycloakx/examples/cloudnative-pg/readme.md
Adding an example deployment, which does not rely on the bitnami psql chart.
=> Example CloudNative PG
